"""AISF control tags for bedrock_assessments findings.

GENERATED by aisf-parity/gen_compliance_maps.py from aisf-parity/aisf-work-ledger.json.
Do not hand-edit: change the ledger, re-run the generator, and re-run
aisf-parity/check_ledger.py, whose gate 14 compares this file against the ledger
in both directions.

The filename carries the module name because the test suite loads several
producers into one interpreter with each module directory on sys.path. A shared
`aisf_compliance.py` would be cached under that bare name and the first loader
would win, silently returning "" for every other module's check ids.

Qualifier vocabulary:
    AISF <control>                  this check alone asserts the whole control
    AISF <control> (1 of N checks)  the control is fully asserted, by this check
                                    together with N-1 others
    AISF <control> (partial)        this check asserts less than the control
                                    requires; the tightening is still outstanding

A tag is a traceability reference, not a statement that the control passed. The
row's own Status column carries the verdict.
"""

AISF_COMPLIANCE_MAP = {
    "BR-04": "AISF AIR-BDR-MDL-02 (1 of 2 checks)",
    "BR-06": "AISF AIR-BDR-KB-06 | AISF AIR-BDR-MDL-07",
    "BR-07": "AISF AIR-BDR-MDL-08 (partial)",
    "BR-10": "AISF AIR-BDR-GRD-01",
    "BR-12": "AISF AIR-BDR-MDL-02 (1 of 2 checks)",
    "BR-20": "AISF AIR-BDR-KB-03",
    "BR-26": "AISF AIR-BDR-GRD-03",
    "BR-27": "AISF AIR-BDR-GRD-09",
    "BR-32": "AISF AIR-BDR-GRD-04",
    "BR-34": "AISF AIR-BDR-GRD-02",
    "BR-37": "AISF AIR-BDR-MDL-10",
    "BR-41": "AISF AIR-BDR-GRD-10",
    "BR-42": "AISF AIR-BDR-MDL-01",
    "BR-43": "AISF AIR-BDR-MDL-03",
    "BR-44": "AISF AIR-BDR-MDL-04",
    "BR-45": "AISF AIR-BDR-MDL-09",
    "BR-46": "AISF AIR-BDR-KB-01",
}


def aisf_frameworks(check_id: str) -> str:
    """The AISF tag for a check id, or "" when the ledger maps none to it."""
    return AISF_COMPLIANCE_MAP.get(check_id, "")
